import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthNavbar from '@/components/AuthNavbar';
import noAuthNavbar from "@/components/noAuthNavbar";
import { getServerSession } from 'next-auth/next';
import { authOptions } from '@/lib/auth'; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=author@1&display=swap"
          rel="stylesheet"/>
      </head>
      <body>
        <AuthNavbar/> 
        {children}
      </body>
    </html>
  );
}

