import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthNavbar from '@/components/AuthNavbar';
<<<<<<< Updated upstream
import noAuthNavbar from "@/components/noAuthNavbar";
import { getServerSession } from 'next-auth/next';
import { authOptions } from '@/lib/auth'; 
=======
import NoAuthNavbar from "@/components/NoAuthNavbar";
import SupabaseProvider from '@/components/SupabaseProvider' 
<<<<<<< Updated upstream
<<<<<<< Updated upstream
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
<<<<<<< Updated upstream
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=author@1&display=swap"
          rel="stylesheet"/>
      </head>
      <body>
        <AuthNavbar/> 
=======
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SupabaseProvider>
          <div className="container mx-auto px-4">
            <h1 className="text-3xl font-bold mb-4">Uina</h1>
          </div>
        {isLoggedIn ? <AuthNavbar /> : <NoAuthNavbar />}
>>>>>>> Stashed changes
        {children}
        </SupabaseProvider>
      </body>
    </html>
  );
}

